services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: image_db
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
  worker:
    build: .
    command: celery -A worker.tasks worker --loglevel=info
    depends_on:
      - redis
